sudo: required
services:
  - docker

before_install:
  - docker build -t cpparkin123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cpparkin123/react-test npm test
after_success:
  - docker build -t chrisp123/multi-client ./client
  - docker build -t chrisp123/multi-nginx ./nginx
  - docker build -t chrisp123/multi-server ./server
  - docker build -t chrisp123/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chrisp123/multi-client
  - docker push chrisp123/multi-nginx
  - docker push chrisp123/multi-server
  - docker push chrisp123/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-732126175301'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
